## Fetch the remote terraform module
deps:
	terraform init

## Reset this project
reset:
	rm -rf Makefile *.tf .terraform

## Coldstart setup
coldstart:
	terraform apply -target module.dns
	terraform apply -target module.acm_request_certificate
	terraform apply
