version: '1.0'

stages:
  - Prepare
  - Build
  - Push

steps:
  main_clone:
    title: "Clone repository"
    type: git-clone
    stage: Prepare
    description: "Initialize"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: CF-default
    revision: ${{CF_REVISION}}

  build_image:
    title: Build image
    stage: Build
    type: build
    description: Build image
    image_name: ${{CF_REPO_NAME}}
    dockerfile: Dockerfile

  push_image_commit:
    title: Push image with commit tag
    stage: Push
    type: push
    candidate: ${{build_image}}
    tags:
    - "${{CF_REVISION}}"