name: 'aws-nuke'

on:
  # Enable pull request for testing
  pull_request: 
    types: [opened, synchronize, reopened]

  # Nuke testing account nightly
  schedule:
    - cron:  '0 0 * * *'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: dry-run
        uses: "docker://quay.io/rebuy/aws-nuke:v2.14.0"
        with:
          args: "--config .github/aws-nuke.yaml --force"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"      
  no-dry-run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: nuke
        uses: "docker://quay.io/rebuy/aws-nuke:v2.14.0"
        with:
          args: "--config .github/aws-nuke.yaml --force --no-dry-run"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_KEY: "${{ secrets.AWS_SECRET_KEY }}"
