name: 'aws-nuke'

on:
  # Enable manual runs
  workflow_dispatch:
  
  # Enable pull request for testing
  pull_request: 
    types: [opened, synchronize, reopened]

  # Nuke testing account nightly
  schedule:
    - cron:  '0 0 * * *'

jobs:
  # Run aws-nuke simulation (don't actually delete anything)
  dry-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: aws-nuke
        uses: "docker://quay.io/rebuy/aws-nuke:v2.15.0"
        with:
          args: "--config .github/aws-nuke.yaml --force"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  # Run aws-nuke "for reals" (delete everything)
  no-dry-run:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: aws-nuke
        uses: "docker://quay.io/rebuy/aws-nuke:v2.15.0"
        with:
          args: "--config .github/aws-nuke.yaml --force --no-dry-run"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
